### ISSUE TITLE
[QUESTION] question about suggestions n shit

### ISSUE THREAD

**Issue by Miskept** [crowplexus/Forever-Engine#2]
Previously on your twitter you wanted people to come here and suggest stuff for the engine.

Do you have any things you planned to add before people start suggesting so you don't get suggested anything you already plan on doing?

**Comment by CrowPlexus** [comment]
like I mentioned on twitter, I planned to add a character offset editor, due to the poll I made, forever is now gonna have fully softcoded characters

**Comment by CrowPlexus** [comment]
I don't have that many ideas in mind so I'm just planning to overhaul the source code and make stuff easier to navigate and extend, making the source more reliable
