### ISSUE TITLE
[HELP] Mine Notes

### ISSUE THREAD

**Issue by Sonicgamer2000** [crowplexus/Forever-Engine#4]
**Prerequisites:**
The title says it all
**Information:**
What is the mine note and what does it do?

**Comment by CrowPlexus** [comment]
it acts as a damage note, it deals damage if you hit it and does nothing if you miss

**Comment by Sonicgamer2000** [comment]
alright. how do you toggle it though?

**Comment by CrowPlexus** [comment]
get the dev version of forever and compile it, then go into the chart editor and select it with the notetype selector https://github.com/CrowPlexus/Forever-Engine/tree/dev
